# Generated by Django 5.2.1 on 2025-05-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0004_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='venue_controled',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='venue_controlled',
            field=models.ManyToManyField(blank=True, to='bands.venue'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='musician_profiles',
            field=models.ManyToManyField(blank=True, to='bands.musician'),
        ),
    ]
